apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aidoor.fullname" . }}
  labels:
    {{- include "aidoor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "aidoor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "aidoor.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "{{ .Values.global.environment }}"
            - name: DataProtection__Key
              valueFrom:
                secretKeyRef:
                  name: {{ include "aidoor.fullname" . }}-auth-keys
                  key: dataProtectionKey
            - name: TZ
              value: "Asia/Shanghai"
          volumeMounts:
            - name: config-volume
              mountPath: /app/appsettings.json
              subPath: appsettings.json
            - name: uploads-volume
              mountPath: {{ .Values.config.fileStorage.uploadDirectory }}
            - name: keys-volume
              mountPath: /app/keys
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "aidoor.fullname" . }}-config
        - name: uploads-volume
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "aidoor.fullname" . }}-uploads-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: keys-volume
          configMap:
            name: {{ include "aidoor.fullname" . }}-keys 