resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: api-env
    literals:
      - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES=true
      - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES=true
      - OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY=in_memory
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard.otlp:18889
      - OTEL_SERVICE_NAME=aidoor-api
      - ASPNETCORE_HTTP_PORTS=8080
