apiVersion: apps/v1
kind: Deployment
metadata:
  name: aidoor-admin
  namespace: aidoor
  labels:
    app: aidoor-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aidoor-admin
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: aidoor-admin
    spec:
      containers:
        - name: aidoor-admin
          image: ${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
