apiVersion: v1
kind: Service
metadata:
  name: aidoor-admin
  namespace: aidoor
  labels:
    app: aidoor-admin
spec:
  selector:
    app: aidoor-admin
  ports:
    - port: 80
      targetPort: 80
      name: http
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aidoor-admin-ingress
  namespace: aidoor
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - admin.thedoorofai.com
      secretName: thedoorofai.com
  rules:
    - host: admin.thedoorofai.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: aidoor-admin
                port:
                  number: 80
