apiVersion: v1
kind: Service
metadata:
  name: aidoor-app
  namespace: aidoor
  labels:
    app: aidoor-app
spec:
  selector:
    app: aidoor-app
  ports:
    - port: 80
      targetPort: 80
      name: http
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aidoor-app-ingress
  namespace: aidoor
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: apisix
  tls:
    - hosts:
        - app.thedoorofai.com
      secretName: thedoorofai.com
  rules:
    - host: app.thedoorofai.com # 使用实际域名
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: aidoor-app
                port:
                  number: 80
