apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-redis-config
  labels:
    app: {{ .Release.Name }}-redis
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  redis.conf: |-
    # Redis配置文件
    port 6379
    dir /data
    {{- if .Values.auth.enabled }}
    requirepass ${REDIS_PASSWORD}
    {{- end }}
    
    # 内存设置
    maxmemory {{ .Values.settings.maxmemory }}
    maxmemory-policy {{ .Values.settings.maxmemoryPolicy }}
    
    # 持久化设置
    save 900 1
    save 300 10
    save 60 10000
    appendonly yes
    appendfsync everysec 