apiVersion: v2
name: redis
description: A custom Redis Helm chart for AIDoor
type: application
version: 1.0.0
appVersion: "7.0.10"
maintainers:
  - name: AIDoor Team
keywords:
  - redis
  - cache
  - database
