# 全局设置
global:
  environment: production

# 应用镜像设置
image:
  repository: registry.cn-beijing.aliyuncs.com/wdora/ai-api
  tag: latest
  pullPolicy: Always

# 副本数量
replicaCount: 2

# 资源配置
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

# 应用配置
config:
  logging:
    level: Information
  fileStorage:
    uploadDirectory: /app/App_Data/uploads
    maxFileSize: 10485760

# 持久化存储
persistence:
  enabled: true
  storageClass: standard
  size: 10Gi

# 网络配置
service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
  hosts:
    - host: api.aidoor.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: aidoor-tls-secret
      hosts:
        - api.aidoor.example.com

# 健康检查
livenessProbe:
  httpGet:
    path: /healthz
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /healthz
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5

# 密钥配置
secrets:
  dataProtectionKey: "RFr9z0QPp8LNDX3rNwxgLTQVm1BBmXTmOyQJpTDCrpM="

# Redis配置
redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: true
    password: ""
    existingSecret: ""
    existingSecretPasswordKey: ""
  master:
    persistence:
      enabled: true
      size: 8Gi
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 2000m
  replica:
    replicaCount: 0
  metrics:
    enabled: true
