name: AIDoor API Deploy

on:
  push:
    branches: ["main"]
    paths:
      - "api/**"
  pull_request:
    branches: ["main"]
    paths:
      - "api/**"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 生成短时间戳标签
      - name: Generate short timestamp
        id: timestamp
        run: echo "SHORT_TS=$(date +%m%d%H%M)" >> $GITHUB_OUTPUT

      # 缓存 NuGet 包
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json', '**/Project.Assets.json', '**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      # 缓存 Docker 层
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-beijing.aliyuncs.com
          username: gmmtec
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./api
          file: ./api/AIDoor.WebAPI/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            registry.cn-beijing.aliyuncs.com/wdora/ai-api:latest
            registry.cn-beijing.aliyuncs.com/wdora/ai-api:${{ steps.timestamp.outputs.SHORT_TS }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          build-args: |
            BUILD_VERSION=${{ steps.timestamp.outputs.SHORT_TS }}

      # 维护缓存大小，移动缓存
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      # 只有在推送到主分支且不是PR时才执行部署
      - name: Install Helm
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        uses: azure/setup-helm@v3
        with:
          version: "v3.11.1"

      - name: Set up kubeconfig
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        uses: azure/k8s-set-context@v3
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy with Helm
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: |
          # 创建命名空间（如果不存在）
          kubectl create namespace aidoor --dry-run=client -o yaml | kubectl apply -f -

          # 构建Helm依赖
          cd ./api/helm/aidoor
          helm dependency build
          cd ../../../

          # 如果有Helm chart，使用以下命令
          helm upgrade --install aidoor ./api/helm/aidoor \
            --namespace aidoor \
            -f ./api/helm/aidoor/values-prod.yaml \
            --set image.repository=registry.cn-beijing.aliyuncs.com/wdora/ai-api \
            --set image.tag=${{ steps.timestamp.outputs.SHORT_TS }} \
            --wait
