name: AIDoor API Deploy

on:
  push:
    branches: ["main"]
    paths:
      - "api/**"
  pull_request:
    branches: ["main"]
    paths:
      - "api/**"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 生成短时间戳标签
      - name: Generate short timestamp
        id: timestamp
        run: echo "SHORT_TS=$(date +%m%d%H%M)" >> $GITHUB_OUTPUT

      # 缓存 NuGet 包
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json', '**/Project.Assets.json', '**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      # 缓存 Docker 层
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-beijing.aliyuncs.com
          username: gmmtec
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./api
          file: ./api/AIDoor.WebAPI/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            registry.cn-beijing.aliyuncs.com/wdora/ai-api:latest
            registry.cn-beijing.aliyuncs.com/wdora/ai-api:${{ steps.timestamp.outputs.SHORT_TS }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          build-args: |
            BUILD_VERSION=${{ steps.timestamp.outputs.SHORT_TS }}

      # 维护缓存大小，移动缓存
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      # 只有在推送到主分支且不是PR时才执行部署
      - name: Set up SSH and deploy
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: |
          # 设置SSH
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H app.thedoorofai.com >> ~/.ssh/known_hosts

          # 准备部署脚本
          cat > deploy.sh << 'EOF'
          #!/bin/bash
          set -e

          # 创建aidoor命名空间（如果不存在）
          kubectl get namespace aidoor > /dev/null 2>&1 || kubectl create namespace aidoor

          # 检查认证密钥是否已存在
          if ! kubectl get secret aidoor-auth-keys -n aidoor > /dev/null 2>&1; then
            echo "生成新的数据保护密钥..."
            DATA_PROTECTION_KEY=$(openssl rand -base64 32)
            
            kubectl create secret generic aidoor-auth-keys \
                --namespace=aidoor \
                --from-literal=dataProtectionKey="$DATA_PROTECTION_KEY"
            echo "数据保护密钥已创建。"
          else
            echo "使用现有数据保护密钥。"
          fi

          # 使用环境变量替换占位符并应用
          REGISTRY="registry.cn-beijing.aliyuncs.com/wdora/ai-api"
          TAG="${{ steps.timestamp.outputs.SHORT_TS }}"

          # 将k8s配置文件下载到服务器
          cat > aidoor-webapi.yaml << 'YAML_EOF'
          $(cat ./api/k8s/aidoor-webapi.yaml)
          YAML_EOF

          # 替换变量并应用
          sed -i "s|\${REGISTRY}|${REGISTRY}|g" aidoor-webapi.yaml
          sed -i "s|\${TAG}|${TAG}|g" aidoor-webapi.yaml

          kubectl apply -f aidoor-webapi.yaml
          kubectl rollout status deployment/aidoor-webapi -n aidoor
          EOF

          # 将部署脚本复制到服务器并执行
          scp deploy.sh root@app.thedoorofai.com:~/deploy.sh
          ssh root@app.thedoorofai.com "chmod +x ~/deploy.sh && ~/deploy.sh"
